# Generated by Django 3.1.4 on 2021-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='최대 200자까지 입력가능합니다.', max_length=200),
        ),
    ]
