# Generated by Django 3.1.4 on 2021-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210409_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='choice',
            field=models.CharField(choices=[('1', 'movie'), ('2', 'drama'), ('3', 'programming')], default='1', max_length=3),
        ),
    ]
